name: Build Environments

on:
  workflow_dispatch: # For demonstration purposes

  # push: # Runs workflow when you push a commit or tag
  #   branches:
  #     - main

jobs:
  register-environments-staging:
    name: Register Environments in Staging
    runs-on: ubuntu-latest

    environment:
      name: Staging

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: "./.github/templates/install-dependencies"
        with:
          workspace_resource_group: ${{ secrets.RESOURCE_GROUP }}
          workspace_name: ${{ secrets.WORKSPACE_NAME }}
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Register training environment
        uses: "./.github/templates/create-environment"
        with:
          environment_file: ./core/environments/train.yml

      - name: Register scoring environment
        uses: "./.github/templates/create-environment"
        with:
          environment_file: ./core/environments/score.yml

      - name: Register drift environment
        uses: "./.github/templates/create-environment"
        with:
          environment_file: ./core/environments/drift.yml

  register-environments-production:
    name: Register Environments in Production
    runs-on: ubuntu-latest
    needs: register-environments-staging

    environment:
      name: Production

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: "./.github/templates/install-dependencies"
        with:
          workspace_resource_group: ${{ secrets.RESOURCE_GROUP }}
          workspace_name: ${{ secrets.WORKSPACE_NAME }}
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Register training environment
        uses: "./.github/templates/create-environment"
        with:
          environment_file: ./core/environments/train.yml

      - name: Register scoring environment
        uses: "./.github/templates/create-environment"
        with:
          environment_file: ./core/environments/score.yml

      - name: Register drift environment
        uses: "./.github/templates/create-environment"
        with:
          environment_file: ./core/environments/drift.yml
